---
# tasks file for sample-apache
tasks:
 - name: Ensure Apache is installed
   ansible.builtin.package:
     name:
             - httpd
             - mod_ssl
             - php
     state: present
 
 - name: Start Apache service
   ansible.builtin.service:
     name: httpd
     state: started
     enabled: true


 - name: firewall configuration
   ansible.posix.firewalld:
           port:
                   - 80/tcp
                   - 443/tcp
           permanent: true
           state: enabled

 - name: Create index.html from template
   ansible.builtin.template:
     src: index.html.j2
     dest: /var/www/html/index.html
   notify: restart apache service

handlers:
 - name: restart apache service
   ansible.builtin.service:
           name: httpd
           state: restarted
