---
- name: haproxy
  hosts: proxy
  become: true

  roles:
    - geerlingguy.haproxy

  vars:
    haproxy_backend_mode: http
    haproxy_backend_balance_method: roundrobin

    haproxy_backend_servers:
      - name: web1
        address: ansible1.hl.local:80
      - name: web2
        address: ansible2.hl.local:80

    haproxy_frontend_port: 80
    haproxy_frontend_mode: http
