- name: Install base packages
  dnf:
    name:
      - curl
      - vim-enhanced
      - net-tools
      - ca-certificates
      - firewalld
    state: present
    update_cache: yes


- name: Enable and start firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: Add project host entries
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE HA PROJECT HOSTS"
    block: |
      192.168.56.113 proxy1
      192.168.56.114 proxy2
      192.168.56.111 webserver1
      192.168.56.112 webserver2
      {{ vip }} {{ domains.hafifa }} {{ domains.clouds }}

- name: Copy Root CA certificate
  copy:
    src: certs/rootCA.crt
    dest: /etc/pki/ca-trust/source/anchors/ha-project-rootCA.crt
    owner: root
    group: root
    mode: '0644'
  notify: Update CA trust
