[control]
control-node ansible_connection=local

[proxies]
proxy1 ansible_host=192.168.56.113 keepalived_state=MASTER keepalived_priority=100
proxy2 ansible_host=192.168.56.114 keepalived_state=BACKUP keepalived_priority=90

[webservers]
webserver1 ansible_host=192.168.56.111 site_name=hafifa
webserver2 ansible_host=192.168.56.112 site_name=clouds

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
