- name: Common setup
  hosts: all
  become: true
  roles:
    - common

- name: Install and configure Nginx webservers
  hosts: webservers
  become: true
  roles:
    - nginx

- name: Install and configure HAProxy and Keepalived
  hosts: proxies
  become: true
  roles:
    - haproxy
    - keepalived
